#!/bin/dash
#author   niraj
#github   niraj998

workspace0() {

# when you have two monitors and turn off screen 0 name of the second monitor becomes 0 and your workspaces gets pushed to to the front this part of script deals with that. always show correct values and align with keyboard shortcuts.
ws=$(wmctrl -d | awk '{print $9}' | head -n 1 )
ws1=$ws
ws2=$(($ws1 + 1 ))
ws3=$(( $ws2 + 1 ))
ws4=$(( $ws3 + 1 ))
ws0=$(( $ws4 + 1 ))
ws5=$([ $ws0 = "10" ] && echo "0" || echo "$ws0")

# Unoccupied
un="0"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
o5=$(bspc query -D -d .occupied --names | grep "$ws5" )

# check if Focused
f1=$(bspc query -D -d focused --names | grep "$ws1" )
f2=$(bspc query -D -d focused --names | grep "$ws2" )
f3=$(bspc query -D -d focused --names | grep "$ws3" )
f4=$(bspc query -D -d focused --names | grep "$ws4" )
f5=$(bspc query -D -d focused --names | grep "$ws5" )

# check if Urgent
# u1=$(bspc query -D -d .urgent --names | grep 1)
# u2=$(bspc query -D -d .urgent --names | grep 2)
# u3=$(bspc query -D -d .urgent --names | grep 3)
# u4=$(bspc query -D -d .urgent --names | grep 4)
# u5=$(bspc query -D -d .urgent --names | grep 5)

echo 	"(box	:class \"workspaces\"	:orientation \"h\" :spacing 5 (button :onclick \"bspc desktop -f $ws1\"	:class	\"$un$o1$f1\"	\"󰈹\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2\"	 \"\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3\" \"󰉋\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4\"	\"󰓇\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5\" \"󰟴\"))"

}
workspace1() {

# Unoccupied
un="0"

# check if Occupied
o6=$(bspc query -D -d .occupied --names | grep 6)
o7=$(bspc query -D -d .occupied --names | grep 7)
o8=$(bspc query -D -d .occupied --names | grep 8)
o9=$(bspc query -D -d .occupied --names | grep 9)
o10=$(bspc query -D -d .occupied --names | grep 0)

# check if Focused
f6=$(bspc query -D -d focused --names | grep 6)
f7=$(bspc query -D -d focused --names | grep 7)
f8=$(bspc query -D -d focused --names | grep 8)
f9=$(bspc query -D -d focused --names | grep 9)
f10=$(bspc query -D -d focused --names | grep 0)

# check if Urgent
# u1=$(bspc query -D -d .urgent --names | grep 1)
# u2=$(bspc query -D -d .urgent --names | grep 2)
# u3=$(bspc query -D -d .urgent --names | grep 3)
# u4=$(bspc query -D -d .urgent --names | grep 4)
# u5=$(bspc query -D -d .urgent --names | grep 5)


echo 	"(box	:class \"workspaces\"	:orientation \"h\"	:spacing 5 (button :onclick \"bspc desktop -f 6\"	:class	\"$un$o6$f6\"	\"󰈹\") (button :onclick \"bspc desktop -f 7\"	:class \"$un$o7$f7\"	 \"\") (button :onclick \"bspc desktop -f 8\"	:class \"$un$o8$f8\" \"󰉋\") (button :onclick \"bspc desktop -f 9\"	:class \"$un$o9$f9\"	\"󰓇\") (button :onclick \"bspc desktop -f 0\"	:class \"$un$o10$f10\" \"󰟴\"))"

}


case $1 in
	0)
	workspace0
	bspc subscribe desktop node_transfer | while read -r _ ; do
	workspace0
	done

	;;

	1)
	workspace1
	bspc subscribe desktop node_transfer | while read -r _ ; do
	workspace1
	done
esac
