#!/bin/sh
# author    niraj
# github    niraj998


# this should only works with two screens

screen1=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | head -n 1)
screen2=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | tail -n 1)

[ "$screen1" = "$screen2" ] && notify-send "Second display not available" && exit

case $1 in 
	laptop)
	xrandr --output $screen1 --auto
	xrandr --output $screen2 --off
	bspc wm -r
	;;

	monitor)
	xrandr --output $screen2 --auto
	xrandr --output $screen1 --off
	bspc wm -r
	;;

	dual)
	xrandr --output $screen1 --auto
	xrandr --output $screen2 --right-of $screen1 --auto
	bspc wm -r
esac

