#!/bin/dash
# author    niraj
# github    niraj998

# this should only works with two screens

screen1=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | head -n 1)
screen2=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | tail -n 1)

[ "$screen1" = "$screen2" ] && notify-send "Second display not available" && exit


restart() {
# Awesome WM
# echo 'awesome.restart()' | awesome-client

# BSPWM
bspc wm -r

}


case $1 in 
	laptop)
	xrandr --output $screen1 --auto 
	xrandr --output $screen2 --off 
  restart 
	;;

	monitor)
	xrandr --output $screen2 --auto 
	xrandr --output $screen1 --off 
  restart 
	;;

	dual)
	xrandr --output $screen1 --auto 
	xrandr --output $screen2 --right-of $screen1 --auto 
  restart 
  ;;
esac

