#!/bin/sh


if [ -x "$(command -v pacman)" ]; then
  alias pacman="sudo pacman"
  alias pacQq="pacman -Qq"

elif [ -x "$(command -v emerge)" ]; then
  alias emerge="sudo emerge"
  alias emaint="sudo emaint"
  alias dispatch-conf="sudo dispatch-conf"
  alias emerge-webrsync="sudo emerge-webrsync"
  alias genkernel="sudo genkernel"

elif [ -x "$(command -v zypper)" ]; then
  alias zypper="sudo zypper --color -v -s 4"

elif [ -x "$(command -v xbps-install)" ]; then
  alias xbps-install="sudo xbps-install -Sfv"
  alias xbps-remove="sudo xbps-remove -Rov"
  alias xbps-up="sudo xbps-install -Suv"
  alias xbps-qr="xbps-query -Rs"
  alias xbps-pkglist="xbps-query -l | awk '{ print $2 }' | xargs -n1 xbps-uhelper getpkgname"

elif [ -x "$(command -v apt)" ]; then
  alias apt="sudo apt"

elif [ -x "$(command -v dnf)" ]; then
  alias dnf="sudo dnf"
  alias yum="sudo yum"

fi

# Power
alias suspend="sudo systemctl suspend"
alias reboot="sudo reboot"
alias poweroff="sudo poweroff"
alias shutdown="sudo shutdown"

# Mounting
alias umount="sudo umount -l"
alias mount="sudo mount"

# Files
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"

alias updatedb="sudo updatedb"
alias bc="bc -ql"
alias yt="yt-dlp --embed-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias ip="ip -color=auto"
alias lf="lfub"
alias ka="killall"
alias g="git"
alias v="$EDITOR"
alias p="pacman"
alias z="zathura"
alias l="clear"
alias lf="lfub"


# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

