#!/bin/sh

# autostart programs
xrandr --dpi 96
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="mpd pipewire"
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# wait for xrdb command
[ -n "$xrdbpid" ] && wait "$xrdbpid"
